### ISSUE TITLE
Letter cases in bitrate: Bytes or or bits?

### ISSUE THREAD

**Issue by i0ntempest** [sbarex/MediaInfo#12]
The app displays bitrates for video and audio in capital letters (KB, MB etc), which from what I can see with ffprobe, is incorrect. It should display lower case letters for bits.

**Comment by sbarex** [comment]
Yes, you are right, it is a mistake.

But I see that `ffprobe` uses powers of 1000 and not 1024 to display the bitrate. 
What is the most correct convention?

**Comment by i0ntempest** [comment]
Well that’s a whole new rabbit hole to go down… I say we keep things consistent with ffprobe, even though imo for binary bits 1024 is the better one.

**Comment by i0ntempest** [comment]
Thanks for the update! The display is now correct but I couldn't find where to switch between base 1024/1000, can you pls tell me?

**Comment by sbarex** [comment]
On the general settings.

<img width="815" alt="Schermata 2022-04-23 alle 08 25 58" src="https://user-images.githubusercontent.com/1948940/164882915-d17d1577-39f6-4676-861a-cac2e8b849e6.png">
