### ISSUE TITLE
Title tag not shown depending on position

### ISSUE THREAD

**Issue by holvanato** [sbarex/MediaInfo#16]
I stumbled upon a strange thing: if I set the `<title>` tag for an audio file, it is not shown when it's the first tag in a given row. If there's another tag in front, the `<title>` tag is shown normally. To test, I set the `<title>` tag in the first position in row 3, and in the second position after different other tags in rows 4 and 5 respectively (see screenshot).
<img width="703" alt="macOS 2022-12-21 at 13 06 48" src="https://user-images.githubusercontent.com/70724988/209005868-69998ae8-e5f8-426d-afa8-b10f72f8e92c.png">

The result has only 4 rows, row 3 is completely skipped. Rows 4 and 5 correctly show the `<title>` (in this case: "6A - As Long As (Orig)".
<img width="598" alt="macOS 2022-12-21 at 13 06 55" src="https://user-images.githubusercontent.com/70724988/209005952-57a576ee-1d7e-423e-b36b-dc68101f845c.png">

**Comment by sbarex** [comment]
Fixed on release 1.7.1.
