### ISSUE TITLE
Doesn't work with OneDrive

### ISSUE THREAD

**Issue by keirthomasbryant** [sbarex/MediaInfo#17]
I might be wrong but MediaInfo doesn't appear in the context menu of files in the Micorosft OneDrive directory (e.g. /Users/USERNAME/Library/CloudStorage/OneDrive/file.png).

I've added the OneDrive folder to the monitored folders within MediaInfo Preferences, and restarted Finder, and so forth. 

My guess is that the existing OneDrive context menu options are blocking MediaInfo somehow? e.g see pic.  ![Screenshot 2023-01-06 at 2 13 21 pm](https://user-images.githubusercontent.com/40987034/211029300-8319ea6d-6e7b-47b0-8672-f5568de8ad7e.png)

**Comment by ozgurg** [comment]
Same for Google Drive.

**Comment by sbarex** [comment]
It seems to be a limitation imposed by the operating system.
