### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by RalphMichel** [sbarex/MediaInfo#18]
By default, the programme is installed in Italian. How can the language of the user interface be changed?

**Comment by ozgurg** [comment]
(For macOS Ventura)
Settings > General > Language & Region > (at the bottom) Applications > Plus (+) > Application: MediaInfo > Language: Choose yours > Add

**Comment by sbarex** [comment]
What version of operating system do you have? What language is set?

**Comment by RalphMichel** [comment]
macOS Ventura 13.1, Language set is German. @ozgurg: thank you! this has solved my problem.
