### ISSUE TITLE
The duration of the video track in mkv files is wrong

### ISSUE THREAD

**Issue by iderror** [sbarex/MediaInfo#20]
Please see the first screen shot.
<img width="1032" alt="截屏2023-07-09 13 32 37" src="https://github.com/sbarex/MediaInfo/assets/11976771/cc44de75-b78b-4ec7-b93d-c29640f92ff8">
I have used another software (also named MediaInfo) to read the duration of the same file, and the following screen shots are the results.
<img width="704" alt="截屏2023-07-09 13 33 39" src="https://github.com/sbarex/MediaInfo/assets/11976771/46b8d5fe-84aa-4a4d-a731-69bfae3e658e">
This screen shot shows the duration of the container, and the following screen shots shows the duration of the first track.
<img width="573" alt="截屏2023-07-09 13 34 01" src="https://github.com/sbarex/MediaInfo/assets/11976771/901479b2-20ba-4c6c-80ce-4854618f6ddb">

From my observation, the resolved duration of the video track in mkv files is in milliseconds, while the software still treats them in seconds, which leads to a very large duration time in the hh:mm:ss format. 

I have tried all three resolve engines and the behaviors are the same. 

The behavior for mp4 files is correct.

**Comment by sbarex** [comment]
fixed on release 1.7.2.
