### ISSUE TITLE
MediaInfo does not show up when control click

### ISSUE THREAD

**Issue by MasterSpam** [sbarex/MediaInfo#27]
The title says it pretty well...
Media Info is enabled as Finder extension:
<img width="494" alt="SCR-20240212-pybw" src="https://github.com/sbarex/MediaInfo/assets/114105385/b341699d-2c65-4ad2-bc41-63f7c0464a1a">

But in the tab "Finder-Extension" itself there seems to be nothing:
<img width="496" alt="SCR-20240212-pyus" src="https://github.com/sbarex/MediaInfo/assets/114105385/ead470f4-16d2-40fa-90f1-883757993d9d">

In the App itself, my Hard drive is monitored.
I even tried it by just entering one specific folder!
<img width="635" alt="SCR-20240212-pzie" src="https://github.com/sbarex/MediaInfo/assets/114105385/a23b25ba-c128-4552-a51d-c5d79a70bb28">

But when I rightclick a image/video/etc nothing shows up:

<img width="402" alt="SCR-20240212-qani-2" src="https://github.com/sbarex/MediaInfo/assets/114105385/63965c95-3622-4614-84ab-0b0cd0816316">

**Comment by MasterSpam** [comment]
Here are my Information abput my device:

MacBook Pro M1 Max
macOS Sonoma 14.1.1

MediaInfo Version: 1.7.2

**Comment by Rub-z** [comment]
@MasterSpam Same issue. Context menu stopped appearing but I'm unsure when it happened. Just noticed today.

I have the same settings: monitored folders are "/" (whole disk). No menus appear on any of my selected preferences (images/audio/video).

**Comment by Rub-z** [comment]
@MasterSpam I managed to fix the issue accidentally. I had an **Automator** Finder Extension (Workflow) that I updated.

Workflow had the settings: Workflow recieves current: files and folders in finder.app

Once I'd updated this workflow, it seemed to refresh the context menus and the MediaInfo menus reappeared.

**Comment by MasterSpam** [comment]
@Rub-z I sadly can't do this because I have no Automator Workflow on my Mac :(

**Comment by sbarex** [comment]
If you try to monitor a folder inside the user dir and not the root the extension works?

**Comment by MasterSpam** [comment]
> If you try to monitor a folder inside the user dir and not the root the extension works?

@sbarex unfortunately not... I inserted one special folder, which only contained one picture/video.
But nothing has changed

**Comment by sbarex** [comment]
On the Activity Monitor (inside Applications/Utility) can you found one (or more) `MediaInfo Finder Extension` process?

**Comment by MasterSpam** [comment]
> On the Activity Monitor (inside Applications/Utility) can you found one (or more) `MediaInfo Finder Extension` process?

@sbarex yes... but with 0.0 CPU usage...

**Comment by sbarex** [comment]
try to disable the extension, then move the app to the trash. then restore the app in the applications folder, run the app the reenable the extension. The 0 cpu usage is correct, the app uses the cpu only you rightclick on a file in a monitored folder.

**Comment by MasterSpam** [comment]
> try to disable the extension, then move the app to the trash. then restore the app in the applications folder, run the app the reenable the extension. The 0 cpu usage is correct, the app uses the cpu only you rightclick on a file in a monitored folder.

@sbarex Thank you very much for your support! This has actually solved my problem! I deleted the app with "AppCleaner" and with it all the files that were together with the application itself. And that helped!

Thanks again for your help and your nice app! It's really helpful and nice!

Keep up the good work!
