### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by robertimes** [sbarex/MediaInfo#3]
Noob question but how do I use this, how is it installed?
Many thanks!

**Comment by sbarex** [comment]
1. Drag the app on the Applications folder.
2. Start the app.
3. Go to System Preferences > Extensions > Finder Extensions and enable the "MediaInfo Finder Extension".
4. Go back to the application and add the folder to monitor. Only files inside these folders are handled by the app. If you want you can monitor the entire Macintosh HD.
5. If you want you can customize other settings.
6. In the Finder, select a image/video file inside a monitored folder, then right click (or command left click). On the context menu there is the new item "Media info" with the info about the file

**Comment by robertimes** [comment]
Thank you, but where is the "app"? I can only download the entire master folder, it seems.

**Comment by sbarex** [comment]
On the [release](https://github.com/sbarex/MediaInfo/releases) section of the repository.

**Comment by robertimes** [comment]
That's what I was missing, much appreciated, thanks!

**Comment by skoskie** [comment]
Note: Do NOT try to install using Homebrew. There is already another project by the same name available as a cask, so you will end up with the [wrong program](https://mediaarea.net/en/MediaInfo) installed.
