### ISSUE TITLE
Stops working after clicking on an "unsupported" file

### ISSUE THREAD

**Issue by wltb** [sbarex/MediaInfo#33]
After clicking on a _flv_ file, or on a _mp4_ file on a network volume (both encapsulate avc/aac streams), not only does the context menu show no information about these files, but doesn't show information about normal/supported files after that.

To rectify this, I turn the extension off and on again in FinderSyncer (I'm on 15.1.1).

My educated guess is that a crash is not handled gracefully, but I didn't dig deeper.

It would be nice if these files could be supported, or at least the app failed gracefully/restarted.

This behavior is reproducible on my machine, let me know if I should supply more information.

**Comment by sbarex** [comment]
does the problem only occur if the files are on a network folder?

**Comment by wltb** [comment]
> does the problem only occur if the files are on a network folder?

No, the Flash video file is on the main disk.

**Comment by sbarex** [comment]
in the settings, general tab, what is the order of the media engines?

**Comment by sbarex** [comment]
Thanks for reporting, the bug should now be fixed in release 1.7.4.

**Comment by wltb** [comment]
Works! Thank You!
