### ISSUE TITLE
QuickLook Title Bar Implementation?

### ISSUE THREAD

**Issue by csaper** [sbarex/MediaInfo#4]
Hi @sbarex -- I saw your [comment from August](https://github.com/Nyx0uf/qlImageSize/issues/45#issuecomment-686710214) on the qlImageSize issue re: support for current gen OSs.

As sadly Apple deprecated QL generators a few years back, there still doesn't seem to be a viable replacement for [qlImageSize](https://github.com/Nyx0uf/qlImageSize)'s display of key image metadata in the QuickLook preview title bar – image dimensions, resolution and filesize.

MediaInfo certainly provides access to this information, but is still a right-click and a bit of menu navigation away. Any thoughts on extending MediaInfo into the QuickLook Preview modal? Perhaps as an overlay — a la:

![Mockup - QuickLook Preview with MediaInfo Overlay](https://user-images.githubusercontent.com/316563/109742880-d1826e00-7b9d-11eb-8786-6b29d14248d2.png)

Cheers!

**Comment by sbarex** [comment]
HI, is not possible, bacause apple do not allow a quicklook extension (or also the deprecated ql generators) to handle many standard formats (including most video and image formats).
