### ISSUE TITLE
Any plan to Add fileSize info?

### ISSUE THREAD

**Issue by xiaoteshushu** [sbarex/MediaInfo#5]
really nice tool !
Do you have any plan to add filesize information on it ?

**Comment by sbarex** [comment]
In the last commit (1.0b10) I also added the _file size_ information.

**Comment by g-w-g** [comment]
I used qlImageSize and did research the problem with it and catalina - I found out about your tool here, it is really helpful to me as a replacement! I would also need fileSize, could you give us an App in a Zip from your new commit (1.0b10) - I am a user who cannot handle code and compile it myself. Thank you!
