### ISSUE TITLE
Color of info text

### ISSUE THREAD

**Issue by g-w-g** [sbarex/MediaInfo#6]
Very helpful tool :) the info for the own chosen dpi in print is great! 
For me, the color of the info text is too bright and therefore hard to read. At least if one chooses "show info in a submenu" the info could be shown with more contrast to the background.

**Comment by sbarex** [comment]
Are you compiled the source with the last commit?

**Comment by g-w-g** [comment]
No I'm sorry, I have no Idea on how to do that compiling, I'm using the version 1.0 (6) from the Zip File you published.

**Comment by sbarex** [comment]
the release 1.0b6 is old. The current is the b10 (and the b11 is near to the release). The problem is that this app require to be signed ad I do not have a developer account to release the precompiled binary.

**Comment by g-w-g** [comment]
I used qlImageSize and did research the problem with it and catalina - I found out about your tool here, it is really helpful to me as a replacement. I would also need fileSize, could you give us an App in a Zip from your new commit (1.0b10) - I am a user who does not know how to compile code myself. The App 1.0 (6) is running on my system. I disabled System Integrity Protection in order to use XtraFinder on OS 10.15 catalina.

**Comment by sbarex** [comment]
I will try to investigate if there is any possibility to circumvent the need for sign. Unfortunately I switched to Big Sur which is even more restrictive in terms of security.

**Comment by g-w-g** [comment]
I understand. Thank you. Well, at least in Catalina it seems to work with an unsigned app with disabled System Integrity Protection.

**Comment by sbarex** [comment]
The problem seems to be that Xcode refuses to compile if you don't provide the certificate for signing ... I have to study ...

**Comment by g-w-g** [comment]
Tested it from the download MediaInfo.zip - App works great for me :) Thanks a lot!
