### ISSUE TITLE
Monitored Folders

### ISSUE THREAD

**Issue by g-w-g** [sbarex/MediaInfo#7]
Could you explain why it needs the option with the monitored folders? Is it a performance problem for my mac or just for the app itself? Could I run into trouble if I'm monitoring my whole harddrive? Is it a problem to have it always running in the background? Thank you for taking the time to do this helpful work :)

**Comment by sbarex** [comment]
The app uses the Apple Finder Sync API to handle the contextual menu. So _this API require_ to set which folders must be hadled by the custom Extension.

If you want you can choose the root of your disk to handle all folders. (I not tested how works on external/network drive).
Every time you right click on a item, the System call my extension that check if the selected file conform to an image/video/audio type. It this check is successful the extension process the file to fetch his properties and make the menu.

**Comment by g-w-g** [comment]
So there's no performance problems at all - thank you for explaining :)
